# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#
development:
  adapter: postgresql
  encoding: unicode
  database: blog_development
  pool: 5
  username: rbates
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: blog_test
  pool: 5
  username: rbates
  password:


production:
  <<: *default
  database: db/production.sqlite3
